import { ServiceNotConfiguredError } from './errors';

/**
 * Private file store (PLAT-017, SEC-008). There is no public-read path: a file is reached only through
 * a short-lived signed URL issued after the server has authorized the caller.
 */
export const MAX_SIGNED_URL_TTL_SECONDS = 300;

export interface PutPrivateObject {
  key: string;
  body: Uint8Array;
  contentType: string;
}

/** How a signed download presents itself: the file name offered, and the verified type. */
export interface SignedDownloadOptions {
  fileName?: string;
  contentType?: string;
}

export interface PrivateFileStore {
  put(object: PutPrivateObject): Promise<void>;
  createSignedDownloadUrl(
    key: string,
    ttlSeconds: number,
    options?: SignedDownloadOptions,
  ): Promise<string>;
}

export class SignedUrlPolicyError extends Error {
  constructor() {
    super(`Signed URL lifetime must be between 1 and ${MAX_SIGNED_URL_TTL_SECONDS} seconds.`);
    this.name = 'SignedUrlPolicyError';
  }
}

export function assertSignedUrlTtl(ttlSeconds: number): void {
  if (!Number.isInteger(ttlSeconds) || ttlSeconds < 1 || ttlSeconds > MAX_SIGNED_URL_TTL_SECONDS) {
    throw new SignedUrlPolicyError();
  }
}

/**
 * Object keys are generated by the server, never taken from a user-supplied file name: this prevents
 * path traversal and keeps personal data (a customer's name in a file name) out of storage keys.
 */
export function assertSafeObjectKey(key: string): void {
  if (!/^[a-z0-9][a-z0-9/_-]{0,511}$/.test(key) || key.includes('//') || key.includes('..')) {
    throw new Error('UNSAFE_OBJECT_KEY');
  }
}

/** Used whenever S3 is not configured: fails loudly rather than writing to local disk. */
export class UnconfiguredFileStore implements PrivateFileStore {
  put(): Promise<void> {
    return Promise.reject(new ServiceNotConfiguredError('Private file storage', 'S3_BUCKET'));
  }

  createSignedDownloadUrl(_key: string, ttlSeconds: number): Promise<string> {
    // Policy violations surface as rejections, like every other failure of this async contract.
    try {
      assertSignedUrlTtl(ttlSeconds);
    } catch (error) {
      return Promise.reject(error instanceof Error ? error : new Error(String(error)));
    }
    return Promise.reject(new ServiceNotConfiguredError('Private file storage', 'S3_BUCKET'));
  }
}
