import { randomInt } from 'node:crypto';
import { chmodSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Demonstration credentials: generated, never written into the repository.
 *
 * Three rules this file exists to keep:
 *
 * 1. **No password is ever hard-coded.** Each run generates fresh ones from `randomInt`, which draws
 *    from the platform CSPRNG. There is no fallback to a fixed password if generation fails.
 * 2. **No password is ever printed or logged.** The run prints the *path* of the file and nothing
 *    else; the file is the only place a password appears.
 * 3. **The file is ignored by Git** (`.demo-credentials.md` in `.gitignore`). If that entry is ever
 *    removed, `npm run check:secrets` is the backstop — but the entry is the control.
 *
 * The generated passwords go through the ordinary activation and reset flows, so the product's own
 * password policy applies unchanged. Nothing here relaxes it.
 */

/**
 * Deliberately excludes the characters people misread when typing a password from a screen into a
 * login form during a client demonstration: 0/O, 1/l/I. The remaining alphabet is still 57 symbols, so
 * 24 characters is about 140 bits — far beyond anything the policy asks for.
 */
const ALPHABET = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const PASSWORD_LENGTH = 24;

export function generatePassword(): string {
  let out = '';
  for (let index = 0; index < PASSWORD_LENGTH; index += 1) {
    out += ALPHABET[randomInt(ALPHABET.length)];
  }
  return out;
}

export interface CredentialEntry {
  roleLabel: string;
  loginIdentifier: string;
  password: string;
  scopeNote: string;
  /** Present only for an account that holds administrative permissions and therefore needs MFA. */
  totp?: { secret: string; otpauthUri: string; recoveryCodes: string[] };
}

export const CREDENTIALS_FILE = '.demo-credentials.md';

/**
 * Rewrite the credentials file from scratch.
 *
 * Rewritten rather than appended so it can never describe a password that is no longer current: the
 * seed re-establishes every demonstration password on each run, and a stale entry in this file would
 * send someone to a login screen that refuses them.
 */
export function writeCredentialsFile(
  repositoryRoot: string,
  entries: CredentialEntry[],
  meta: { databaseName: string; generatedAt: string; webUrl: string },
): string {
  const path = join(repositoryRoot, CREDENTIALS_FILE);
  const lines: string[] = [
    '# Demonstration credentials — local development only',
    '',
    '> **This file is ignored by Git and must stay that way.** It contains working passwords.',
    '> Do not paste its contents into a chat, an issue, a document, or a screen share.',
    '',
    `Generated: ${meta.generatedAt}`,
    `Database: \`${meta.databaseName}\``,
    `Sign in at: ${meta.webUrl}`,
    '',
    'These accounts exist only in the local development database. The data behind them is fictional',
    '(see `docs/demo/runbook.md`). Every password here was generated by `npm run seed:demo` and is',
    'replaced the next time that command runs.',
    '',
  ];

  for (const entry of entries) {
    lines.push(`## ${entry.roleLabel}`);
    lines.push('');
    lines.push(`- Login: \`${entry.loginIdentifier}\``);
    lines.push(`- Password: \`${entry.password}\``);
    lines.push(`- Data scope: ${entry.scopeNote}`);
    if (entry.totp) {
      lines.push(
        '- **Second factor required** (SEC-017: this account holds administrative permissions).',
      );
      lines.push(`  - Authenticator secret: \`${entry.totp.secret}\``);
      lines.push(`  - Or add by URI: \`${entry.totp.otpauthUri}\``);
      lines.push(
        `  - Recovery codes: ${entry.totp.recoveryCodes.map((c) => `\`${c}\``).join(', ')}`,
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('To remove the demonstration data and these accounts:');
  lines.push('');
  lines.push('```');
  lines.push('npm run seed:demo:reset -- --confirm');
  lines.push('```');
  lines.push('');

  writeFileSync(path, lines.join('\n'), { encoding: 'utf8', mode: 0o600 });
  try {
    // Best effort on Windows, where mode bits are advisory. The .gitignore entry is the real control.
    chmodSync(path, 0o600);
  } catch {
    /* ignore */
  }
  return path;
}
